spring:
  profiles:
    active: dev
---
server:
  port: 8888
spring:
  profiles: dev
  application:
    name: cloudconfigclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
server:
  port: 9999
spring:
  profiles: test
  application:
    name: cloudconfigclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
